version: 0.2

env:
  parameter-store:
    REACT_APP_DOMAIN: REACT_APP_DOMAIN
    REACT_APP_API_URL: REACT_APP_API_URL

phases:
  install:
    runtime-versions:
      python: 3.x
  pre_build:
    commands:
      - pip3 install --upgrade pip3
      - pip3 install boto3
      - pip3 install requests
  build:
    commands:
      - python3 create_test_data.py
