version: 0.2

env:
  parameter-store:
    AWS_COGNITO_IDENTITY_POOL_ID: REACT_APP_AWS_COGNITO_IDENTITY_POOL_ID
    AWS_USER_POOLS_ID: REACT_APP_AWS_USER_POOLS_ID
    AWS_USER_POOLS_WEB_CLIENT_ID: REACT_APP_AWS_USER_POOLS_WEB_CLIENT_ID
    REACT_APP_DOMAIN: REACT_APP_DOMAIN
    REACT_APP_API_URL: REACT_APP_API_URL

phases:
  install:
    runtime-versions:
      python: 3.x
  pre_build:
    commands:
      - pip3 install boto3
      - pip3 install requests
  build:
    commands:
      - python3 create_test_data.py
